version: '3'
services:
  rails:
    container_name: todoApi
    build: rails
    command: >
      ash -c
      "bin/rails s -b 0.0.0.0"
    # tty: true
    volumes:
      - ../:/usr/src/app:z
    ports:
      - "3000:3000"
    links:
      - db
  db:
    container_name: todoDB
    build: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secretsecret
      MYSQL_USER: todo
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: todo
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
